const michiganCityToCounty: Record<string, string> = {
  "Detroit": "WAYNE",
  "Dearborn": "WAYNE",
  "Dearborn Heights": "WAYNE",
  "Ann Arbor": "WASHTENAW",
  "Grand Rapids": "KENT",
  "Lansing": "INGHAM",
  "East Lansing": "INGHAM",
  "Flint": "GENESEE",
  "Sterling Heights": "MACOMB",
  "Warren": "MACOMB",
  "Clinton Township": "MACOMB",
  "Troy": "OAKLAND",
  "Bloomfield Hills": "OAKLAND",
  "Rochester Hills": "OAKLAND",
  "Pontiac": "OAKLAND",
  "Farmington Hills": "OAKLAND",
  "West Bloomfield": "OAKLAND",
  "Livonia": "WAYNE",
  "Westland": "WAYNE",
  "Taylor": "WAYNE",
  "Southfield": "OAKLAND",
  "Royal Oak": "OAKLAND",
  "Kalamazoo": "KALAMAZOO",
  "Muskegon": "MUSKEGON",
  "Saginaw": "SAGINAW",
  "Bay City": "BAY",
  "Midland": "MIDLAND",
  "Jackson": "JACKSON",
  "Battle Creek": "CALHOUN",
  "Portage": "KALAMAZOO",
  "Novi": "OAKLAND",
  "Canton": "WAYNE",
  "Ypsilanti": "WASHTENAW",
  "Holland": "OTTAWA",
  "Traverse City": "GRAND TRAVERSE",
  "Marquette": "MARQUETTE",
  "Petoskey": "EMMET",
  "Alpena": "ALPENA",
  "Mount Pleasant": "ISABELLA",
  "Big Rapids": "MECOSTA",
  "Cadillac": "WEXFORD",
};

export function getMichiganCounty(city: string): string {
  if (!city) return "____________________";
  const county = michiganCityToCounty[city.trim()];
  return county || "____________________";
}
