-- ============================================================
-- Migration: Farewell Videos Storage Bucket Policies
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. Create the bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'farewell-videos',
  'farewell-videos',
  false,
  524288000, -- 500MB
  ARRAY['video/mp4', 'video/quicktime', 'video/webm', 'application/pdf', 'image/jpeg', 'image/png', 'image/jpg']
)
ON CONFLICT (id) DO UPDATE SET
  file_size_limit = 524288000,
  allowed_mime_types = ARRAY['video/mp4', 'video/quicktime', 'video/webm', 'application/pdf', 'image/jpeg', 'image/png', 'image/jpg'];

-- 2. Allow authenticated clients to upload to their own folder
-- Path format: {client_id}/{message_id}/{filename}
-- The first folder segment must match the user's client ID.
DROP POLICY IF EXISTS "Clients can upload own farewell videos" ON storage.objects;
CREATE POLICY "Clients can upload own farewell videos"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'farewell-videos'
    AND (storage.foldername(name))[1] = (
      SELECT id::text FROM clients WHERE profile_id = auth.uid()
    )
  );

-- 3. Allow authenticated clients to read/preview their own videos
DROP POLICY IF EXISTS "Clients can read own farewell videos" ON storage.objects;
CREATE POLICY "Clients can read own farewell videos"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'farewell-videos'
    AND (storage.foldername(name))[1] = (
      SELECT id::text FROM clients WHERE profile_id = auth.uid()
    )
  );

-- 4. Allow authenticated clients to update (upsert) their own videos
DROP POLICY IF EXISTS "Clients can update own farewell videos" ON storage.objects;
CREATE POLICY "Clients can update own farewell videos"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'farewell-videos'
    AND (storage.foldername(name))[1] = (
      SELECT id::text FROM clients WHERE profile_id = auth.uid()
    )
  );

-- 5. Allow authenticated clients to delete their own videos
DROP POLICY IF EXISTS "Clients can delete own farewell videos" ON storage.objects;
CREATE POLICY "Clients can delete own farewell videos"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'farewell-videos'
    AND (storage.foldername(name))[1] = (
      SELECT id::text FROM clients WHERE profile_id = auth.uid()
    )
  );

-- Note: Trustee access to videos is handled server-side via signed URLs
-- generated by the admin client in /api/farewell/access and
-- /api/vault/farewell/[id]/signed-url — no storage policy needed for trustees.

SELECT 'Farewell storage migration complete' AS status;
