// GENERATED FILE — do not edit. Source: trust-funding-instructions-v1.0.0.txt
// Regenerate with: npm run templates:build

const template = `
# TRUST FUNDING INSTRUCTIONS

#sub for the {{trust_name_display_upper}}

Funding your Revocable Living Trust completely is the single most important step left in your plan. A trust that holds nothing, or holds only part of what you own, will not keep your estate out of probate. The instructions below walk you through the process.

For most assets, you will make an ownership change: retitling the asset out of your individual name and into your name as Trustee of your trust.

For certain assets, such as life insurance and retirement accounts, you will instead make a beneficiary change so the asset passes correctly at your death. The beneficiary is not automatically your trust. Review the Retirement Plans and Life Insurance Policies and Annuities sections below.

As a practical matter, moving assets into the trust means signing new documents of title, new deeds for real property, and new signature cards at your bank, along with change-of-beneficiary forms for pension plans, retirement accounts, and insurance policies.

You may need help from your financial advisor, accountant, broker, or insurance agent to complete some of these changes. These instructions cover the common situations but cannot address every possible type of transfer. If you own something that is not discussed here, a licensed attorney can assist you.

Keep proof of every transfer. Place a copy of each document evidencing a trust asset (account statements, deeds, business interests, insurance confirmations, and anything else) in the Trust Assets section of your Vault. The final step for every transfer should be filing something that shows the trust is the owner or beneficiary.

[BOLD_STATUTORY]
The bold line closing each section below tells you exactly what to file.
[/BOLD_STATUTORY]

## USING YOUR CERTIFICATION OF TRUST

Your Trust Package includes a Certification of Trust. It is a short written statement confirming three things:

- that your trust exists;
- that you are one of its Trustees; and
- that you have authority to transact business on the trust's behalf.

Most institutions have their own certification form they will ask you to complete. If the institution has no form of its own, give them a copy of your Certification of Trust. It discloses only what a third party needs to see, without revealing the confidential terms of your plan.

## YOUR TAX IDENTIFICATION NUMBER

While you are living, your Trustee does not need a separate tax identification number for the trust and does not file a separate trust return. The IRS prefers that you continue using your own Social Security number, and all income generated by trust assets is reported on your personal Form 1040.

At your death, the trust becomes irrevocable for tax purposes. It may divide into several trusts, each potentially treated as its own taxable entity for income tax purposes. Your successor Trustee and your accountant can work together at that time so your heirs receive the full benefit of your plan.

## TITLING ASSETS IN YOUR NAME AS TRUSTEE

As a general rule, everything you own now and everything you acquire later should be titled in the name of your trust. Either of the following formats is commonly used:

{{#IF is_joint_trust equals true}}

{{client_full_name}} and {{grantor_2_full_name}}, Trustees of the {{trust_name_display}} dated {{trust_date}}, and any amendments to it

{{/IF}}

{{#IF is_joint_trust equals false}}

{{client_full_name}}, Trustee of the {{trust_name_display}} dated {{trust_date}}, and any amendments to it

{{/IF}}

OR

The {{trust_name_display}} dated {{trust_date}}

## INSTRUCTIONS FOR TRANSFERRING SPECIFIC ASSETS

### Section A — Cash Accounts

Sign new signature and ownership cards to retitle any account of meaningful size (checking and savings, treasury bills, money market accounts, and certificates of deposit) into your name as Trustee. If you would rather leave a small joint or household checking account alone, another common approach is naming your trust as the pay-on-death (POD) beneficiary of that account instead.

Before retitling a certificate of deposit, check with a bank officer to confirm the institution will not treat the name change as an early withdrawal subject to penalty. This is rarely an issue, since the tax identification number on the account does not change.

Direct your financial institution, by letter or in person, to change the account title to the trust. The tax identification number used for withholding and reporting (your Social Security number) stays the same. Where two Trustees are serving, make sure each of them is given signature authority on the account, and sign the new cards as Trustees.

Retitling the bank's records has nothing to do with what is printed on your checks. There is no reason for the trust name to appear there. You can ask the bank to keep printing your individual name.

[BOLD_STATUTORY]
File a copy of the next account statement showing you as Trustee in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section B — Investment Accounts

For publicly traded stocks and bonds already held in a brokerage or investment account, contact the broker or custodian and instruct them to retitle the account in the name of the trust. The process mirrors the one described above for cash accounts. You may be asked to complete a new account application and to produce a copy of your Certification of Trust. Title to the account itself should be in the trust's name.

[BOLD_STATUTORY]
File a copy of the next account statement showing you as Trustee in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section C — Stocks and Bonds Not Held in an Investment Account

If you hold original stock or bond certificates, there are two routes:

- Open a brokerage or investment account in the name of your trust and deposit the certificates into it. (If you prefer, you can later have the broker reissue the certificates to you in the trust's name.) Future statements titled in the trust's name will establish ownership. File a copy of a statement showing trust ownership in the Trust Assets section of your Vault.

- Deal directly with the transfer agent for the security and instruct the agent to reissue the certificate naming your trust as owner. File a copy of the front and back of the reissued certificate in the Trust Assets section of your Vault.

### Section D — Stock Options

Assigning or transferring stock options calls for a close look at the tax and legal consequences. Talk to your CPA and your stock plan administrator about whether and how to assign your interest to your trust. A licensed attorney can also assist with this type of transfer.

### Section E — Personal Effects

Tangible personal property means items such as household furnishings, appliances and fixtures, works of art, motor vehicles, pictures, collectibles, clothing and jewelry, books, sporting goods, and hobby equipment. Ownership of these items is transferred to a Revocable Living Trust by a written assignment. Your Trust Package includes a signed Assignment of Personal Property for this purpose.

[BOLD_STATUTORY]
File a copy of the signed assignment in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

Your personal vehicles can be titled in the trust, but many people choose to leave them out, for two reasons. First, if you are in an accident, the existence of a trust may lead the other parties to assume you have significant assets and encourage a lawsuit. Second, heirs can generally transfer vehicles without opening a formal probate proceeding. If you do decide to title a vehicle in the trust, check with your casualty insurance agent first to make sure the change does not trigger a business rating and raise your premium.

### Section F — Retirement Plans

Never transfer ownership of a qualified retirement plan, pension plan, or individual retirement account into your Revocable Living Trust. Instead, where the plan provides pre-retirement death benefits, many people name their spouse, children, or partner as primary and contingent beneficiaries.

[BOLD_STATUTORY]
Beneficiary designations for retirement accounts raise complicated tax questions and depend heavily on your particular family circumstances. The trade-offs involved affect required minimum distributions and how your benefits are taxed after your death. A licensed attorney or tax professional can help you match the options to your goals.
[/BOLD_STATUTORY]

Your plan administrator should send you a letter confirming the change in its records.

[BOLD_STATUTORY]
File a copy of that confirmation letter (or, if none arrives, the change-of-beneficiary form you submitted) in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section G — Qualified Tuition Plans (529 Plans)

Moving a 529 plan into a Revocable Living Trust is only appropriate if the trust contains specific language allowing the Trustee to administer the account. Speak with a licensed attorney before naming your trust as the owner of a 529 plan.

### Section H — Life Insurance Policies and Annuities

Some people with larger life insurance policies use irrevocable life insurance trusts for estate tax planning. Those trusts are outside the scope of this service, and a licensed attorney can help you decide whether one fits your situation. Even so, you may want some policy proceeds paid directly to your Revocable Living Trust. Your insurance agent can help you settle on the ownership and beneficiary designation for each policy.

If you do name your Revocable Living Trust as a beneficiary, keep the following in mind:

- The beneficiary designation on the policy, not your Will or your trust document, controls who receives the proceeds.

- Many people name their Revocable Living Trust as beneficiary because it brings the proceeds under the terms of the trust. If this is what you want, tell your insurance agent. The agent will either make the change or send you the form to complete.

- If the trust is the primary beneficiary, a secondary beneficiary such as a spouse, partner, or children is commonly named as well.

Each carrier has its own preferred wording. A typical format looks like this:

Primary Beneficiary: The {{trust_name_display}} dated {{trust_date}}

Secondary Beneficiary: Spouse, partner, children, or other heirs

Your insurance company should send you a letter confirming the change to its records.

[BOLD_STATUTORY]
File a copy of that confirmation letter (or, if none arrives, the change-of-beneficiary form you submitted) in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section I — Mortgages, Notes, and Other Receivables

If you have loaned money to anyone, assign your interest as lender to your trust by written document and notify the borrower of the assignment. A licensed attorney can prepare the assignment for your signature.

[BOLD_STATUTORY]
File a copy of each signed assignment in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section J — Partnership Interests

Unless your partnership agreement restricts it, a general partnership interest is transferred by a written assignment signed by you and acknowledged by your partners. A limited partnership interest is transferred the same way. A licensed attorney can prepare these assignments for your signature.

[BOLD_STATUTORY]
File a copy of each signed assignment in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section K — Corporate and Professional Business Interests

Contact your corporate counsel when transferring a business interest into the trust.

- If the business is a corporation, the shares held in your individual name must be cancelled and reissued to you as Trustee. File a copy of the front and back of the new stock certificate in the Trust Assets section of your Vault.

- If the business is a limited liability company, a licensed attorney can draft an assignment transferring your membership interest to the trust. File a copy of the assignment in the Trust Assets section of your Vault.

### Section L — Sole Proprietorships

A sole proprietorship is a business owned by one individual, and it is transferred to a Revocable Living Trust by written assignment. List the tangible property of the business individually or by category within the assignment.

[BOLD_STATUTORY]
File a copy of the signed assignment in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section M — Oil, Gas, and Mineral Interests

How you transfer these interests depends on whether you own them or lease them. If you own the interest outright, record a deed conveying it to your trust. If your interest is a lease, assign your rights as lessee to the trust by written assignment.

[BOLD_STATUTORY]
File a copy of the recorded deed or the signed assignment in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section N — Real Property

Transferring real estate requires attention to both ownership and tax issues, which turn on how the property is currently titled. In every case the transfer will require preparing, signing, and recording a new deed for each parcel, and this should be handled by a licensed attorney.

[BOLD_STATUTORY]
File a copy of each recorded deed in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

Separately, contact your homeowner's insurance provider about adding the trust as an additional endorsee on the policy.

### Section O — Anticipated Inheritance, Gift, or Lawsuit Judgment

If you are a beneficiary of the estate of someone who has already died, or a plaintiff in a pending lawsuit, you can assign that interest to your trust now, protecting it in the event you become disabled or die before the distribution or payment arrives. A licensed attorney can prepare the assignment.

[BOLD_STATUTORY]
File a copy of the signed assignment in the Trust Assets section of your Vault.
[/BOLD_STATUTORY]

### Section P — Reviewing Your Estate Plan

Every estate plan needs ongoing maintenance, so review yours with a licensed attorney every two to three years. A change in your family, a meaningful increase in your net worth, or a change in the tax law can each undercut how well your plan works.

Document preparation service only. Not legal advice. No attorney-client relationship created.
`;

export default template;
