"use client";

import type { VaultItem, CategoryField } from "./vault-constants";

interface VaultCategoryViewProps {
  selectedCategory: string;
  items: VaultItem[];
  downloadingId: string | null;
  deletingId: string | null;
  categories: ReadonlyArray<{ key: string; icon: string; label: string; vaultOnly: boolean }>;
  categoryFields: Record<string, CategoryField[]>;
  onBack: () => void;
  onAddItem: () => void;
  onUploadDoc: () => void;
  onViewItem: (item: VaultItem) => void;
  onDownloadDoc: (item: VaultItem) => void;
  onDeleteItem: (id: string) => void;
}

export default function VaultCategoryView({
  selectedCategory,
  items,
  downloadingId,
  deletingId,
  categories,
  onBack,
  onAddItem,
  onUploadDoc,
  onViewItem,
  onDownloadDoc,
  onDeleteItem,
}: VaultCategoryViewProps) {
  const catItems = items.filter((i) => i.category === selectedCategory);
  const cat = categories.find((c) => c.key === selectedCategory);
  const isEstateDoc = selectedCategory === "estate_document";

  return (
    <div className="max-w-4xl">
      <button
        onClick={onBack}
        className="flex items-center gap-1 text-sm text-navy/60 hover:text-navy mb-4"
      >
        &larr; Back to Vault
      </button>
      <div className="flex items-center justify-between flex-wrap gap-4">
        <h1 className="text-2xl font-bold text-navy">
          {cat?.icon} {cat?.label}
        </h1>
        {isEstateDoc ? (
          <button
            onClick={onUploadDoc}
            className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-2 text-sm font-semibold text-white hover:bg-gold/90 transition-colors"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5"
              />
            </svg>
            Upload Document
          </button>
        ) : (
          <button
            onClick={onAddItem}
            className="inline-flex items-center rounded-full bg-gold px-5 py-2 text-sm font-semibold text-white hover:bg-gold/90 transition-colors"
          >
            + Add New
          </button>
        )}
      </div>

      {isEstateDoc && (
        <p className="mt-2 text-sm text-charcoal/50">
          Upload PDFs of your signed and executed estate documents to keep them securely stored in
          your vault.
        </p>
      )}

      {catItems.length === 0 ? (
        <div className="mt-10 text-center">
          <div className="mx-auto w-14 h-14 rounded-full bg-gray-100 flex items-center justify-center mb-3">
            <span className="text-2xl">{cat?.icon}</span>
          </div>
          <p className="text-sm text-charcoal/50">
            {isEstateDoc
              ? "No documents uploaded yet. Upload your first signed document."
              : "No items yet. Add your first one."}
          </p>
        </div>
      ) : (
        <div className="mt-6 space-y-3">
          {catItems.map((item) => {
            const itemData = item.data as Record<string, unknown>;
            const isUploaded = !!itemData?.storage_path;
            const isAuto = !!itemData?.order_id;
            const isDownloading = downloadingId === item.id;

            return (
              <div
                key={item.id}
                className="rounded-xl bg-white border border-gray-200 p-5 flex items-center justify-between gap-4"
              >
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className="text-sm font-semibold text-navy">{item.label}</p>
                    {isAuto && (
                      <span className="rounded-full bg-navy/10 px-2 py-0.5 text-xs text-navy">
                        Generated by EstateVault
                      </span>
                    )}
                    {isUploaded && !!itemData.doc_type && (
                      <span className="rounded-full bg-gold/10 px-2 py-0.5 text-xs text-gold font-medium">
                        {String(itemData.doc_type)}
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-charcoal/50 mt-1">
                    {isUploaded && itemData.file_name
                      ? `${String(itemData.file_name)} · Uploaded ${new Date(item.created_at).toLocaleDateString()}`
                      : `Added ${new Date(item.created_at).toLocaleDateString()}`}
                  </p>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  {!isEstateDoc && (
                    <button
                      onClick={() => onViewItem(item)}
                      className="inline-flex items-center gap-1.5 rounded-lg bg-navy/10 px-3.5 py-2 text-xs font-semibold text-navy hover:bg-navy/20 transition-colors"
                    >
                      <svg
                        className="w-3.5 h-3.5"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        strokeWidth={2}
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"
                        />
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                        />
                      </svg>
                      View
                    </button>
                  )}
                  {isUploaded && (
                    <button
                      onClick={() => onDownloadDoc(item)}
                      disabled={isDownloading}
                      className="inline-flex items-center gap-1.5 rounded-lg bg-navy px-3.5 py-2 text-xs font-semibold text-white hover:bg-navy/90 disabled:opacity-60 transition-colors"
                    >
                      {isDownloading ? (
                        <div className="w-3 h-3 border-2 border-white/40 border-t-white rounded-full animate-spin" />
                      ) : (
                        <svg
                          className="w-3.5 h-3.5"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth={2}
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"
                          />
                        </svg>
                      )}
                      {isDownloading ? "Opening..." : "Download"}
                    </button>
                  )}
                  {!isAuto && (
                    <button
                      onClick={() => onDeleteItem(item.id)}
                      disabled={deletingId === item.id}
                      className="text-xs text-red-500 hover:text-red-700 transition-colors inline-flex items-center gap-1 disabled:opacity-60 disabled:cursor-not-allowed"
                    >
                      {deletingId === item.id && (
                        <span className="w-3 h-3 border-2 border-red-300 border-t-red-600 rounded-full animate-spin" />
                      )}
                      {deletingId === item.id ? "Deleting..." : "Delete"}
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
