#!/usr/bin/env python3
"""
EstateVault — reference vector generator.

Produces docs/crypto-vectors.json from the spec primitives.
Run once at v1 freeze. Both client implementations (web TS, mobile Dart) must
match this output byte-for-byte.

Requirements:
    pip install pynacl cryptography mnemonic

Usage:
    python scripts/generate-crypto-vectors.py > docs/crypto-vectors.json
"""

import json
import hashlib
import hmac
import os
import sys
from pathlib import Path

import nacl.bindings as sodium
import nacl.utils
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from mnemonic import Mnemonic


def hx(b: bytes) -> str:
    return b.hex()


def hkdf_sha256(ikm: bytes, info: bytes, length: int = 32, salt: bytes = b"\x00" * 32) -> bytes:
    return HKDF(algorithm=hashes.SHA256(), length=length, salt=salt, info=info).derive(ikm)


def argon2id(passphrase: bytes, salt: bytes, m_kib: int, t: int, p: int, out_len: int) -> bytes:
    # pynacl exposes pwhash with argon2id
    return sodium.crypto_pwhash(
        out_len,
        passphrase,
        salt,
        t,
        m_kib * 1024,
        sodium.crypto_pwhash_ALG_ARGON2ID13,
    )


def aead_encrypt(key: bytes, nonce: bytes, ad: bytes, plaintext: bytes) -> bytes:
    return sodium.crypto_aead_xchacha20poly1305_ietf_encrypt(plaintext, ad, nonce, key)


def envelope_encode(version: int, nonce: bytes, ct_with_tag: bytes) -> bytes:
    return b"EV01" + bytes([version]) + nonce + ct_with_tag


def main() -> None:
    out: dict = {
        "$schema_version": 1,
        "spec_version": 1,
        "status": "FROZEN — generated by scripts/generate-crypto-vectors.py",
        "encoding_note": "Hex bytes lowercase. utf8 = raw UTF-8.",
    }

    # KDF
    out["kdf"] = []
    for vid, pp, salt_hex in [
        ("kdf-001", "correct horse battery staple", "00112233445566778899aabbccddeeff"),
        ("kdf-002", "Trustno1!Trustno1!",          "deadbeefdeadbeefdeadbeefdeadbeef"),
    ]:
        salt = bytes.fromhex(salt_hex)
        kek = argon2id(pp.encode(), salt, m_kib=65536, t=3, p=2, out_len=32)
        out["kdf"].append({
            "id": vid,
            "passphrase_utf8": pp,
            "salt_hex": salt_hex,
            "params": {"alg": "argon2id", "v": "0x13", "m": 65536, "t": 3, "p": 2, "out": 32},
            "expected_kek_hex": hx(kek),
        })

    # HKDF (using a fixed IKM = MK)
    ikm = bytes.fromhex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20")
    out["hkdf"] = []
    for vid, info in [
        ("hkdf-db",      "ev:dek:db:v1"),
        ("hkdf-files",   "ev:dek:files:v1"),
        ("hkdf-index",   "ev:idx:hmac:v1"),
        ("hkdf-x25519",  "ev:key:x25519:v1"),
        ("hkdf-ed25519", "ev:key:ed25519:v1"),
    ]:
        okm = hkdf_sha256(ikm, info.encode(), 32)
        out["hkdf"].append({
            "id": vid,
            "ikm_hex": hx(ikm),
            "salt_hex": "00" * 32,
            "info_utf8": info,
            "len": 32,
            "expected_okm_hex": hx(okm),
        })

    # AEAD
    aead_key = bytes.fromhex("1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100")
    aead_nonce = bytes.fromhex("404142434445464748494a4b4c4d4e4f5051525354555657")
    out["aead_bytes"] = [
        {
            "id": "aead-001",
            "algorithm": "xchacha20poly1305-ietf",
            "key_hex": hx(aead_key),
            "nonce_hex": hx(aead_nonce),
            "ad_utf8": "ev:vault_items:v1",
            "plaintext_utf8": '{"label":"Will","data":{"doc_type":"will"}}',
            "expected_ciphertext_hex": hx(aead_encrypt(
                aead_key, aead_nonce, b"ev:vault_items:v1",
                b'{"label":"Will","data":{"doc_type":"will"}}',
            )),
        },
        {
            "id": "aead-002-empty",
            "algorithm": "xchacha20poly1305-ietf",
            "key_hex": hx(aead_key),
            "nonce_hex": hx(aead_nonce),
            "ad_utf8": "",
            "plaintext_hex": "",
            "expected_ciphertext_hex": hx(aead_encrypt(aead_key, aead_nonce, b"", b"")),
        },
    ]

    # Envelope
    env_pt = bytes.fromhex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20")
    env_ct = aead_encrypt(aead_key, aead_nonce, b"ev:mk-wrap:v1", env_pt)
    out["envelope"] = [{
        "id": "env-001",
        "magic_ascii": "EV01",
        "version": 1,
        "nonce_hex": hx(aead_nonce),
        "key_hex": hx(aead_key),
        "ad_utf8": "ev:mk-wrap:v1",
        "plaintext_hex": hx(env_pt),
        "expected_envelope_hex": hx(envelope_encode(1, aead_nonce, env_ct)),
    }]

    # Mnemonic
    mn = "abandon " * 23 + "art"
    seed = Mnemonic("english").to_seed(mn, passphrase="")
    kek_recovery = hkdf_sha256(seed, b"ev:kek:recovery:v1", 32)
    out["mnemonic"] = [{
        "id": "mnemonic-001",
        "wordlist": "english",
        "mnemonic": mn,
        "expected_seed_hex": hx(seed),
        "info_utf8": "ev:kek:recovery:v1",
        "expected_kek_recovery_hex": hx(kek_recovery),
    }]

    # Keypair derivation
    seed_x = hkdf_sha256(ikm, b"ev:key:x25519:v1", 32)
    pk_x, sk_x = sodium.crypto_box_seed_keypair(seed_x)
    seed_e = hkdf_sha256(ikm, b"ev:key:ed25519:v1", 32)
    pk_e, sk_e = sodium.crypto_sign_seed_keypair(seed_e)
    out["keypair"] = [
        {"id": "kp-x25519-001",  "seed_hex": hx(seed_x),
         "expected_pub_hex": hx(pk_x), "expected_priv_hex": hx(sk_x)},
        {"id": "kp-ed25519-001", "seed_hex": hx(seed_e),
         "expected_pub_hex": hx(pk_e), "expected_priv_hex": hx(sk_e)},
    ]

    # Blind index
    idx_key = hkdf_sha256(ikm, b"ev:idx:hmac:v1", 32)
    norm = "last will and testament"
    bi = hmac.new(idx_key, norm.encode(), hashlib.sha256).digest()[:16]
    out["blind_index"] = [{
        "id": "blind-001",
        "key_hex": hx(idx_key),
        "input_utf8": "Last Will and Testament",
        "normalized_utf8": norm,
        "truncate_bytes": 16,
        "expected_hmac_hex": hx(bi),
    }]

    # Sealed box (non-deterministic, only roundtrip)
    out["sealed_box"] = [{
        "id": "seal-001",
        "recipient_pub_hex":  hx(pk_x),
        "recipient_priv_hex": hx(sk_x),
        "plaintext_hex": hx(env_pt),
        "note": "sealed_box uses ephemeral sender key — verify via roundtrip equality",
        "expected_roundtrip_plaintext_hex": hx(env_pt),
    }]

    # Audit signature (deterministic Ed25519)
    record = ('{"action":"vault.item_create",'
              '"actor":"00000000-0000-0000-0000-000000000001",'
              '"ciphertext_hash":"' + "00" * 32 + '",'
              '"hash_prev":"' + "00" * 32 + '",'
              '"resource":"00000000-0000-0000-0000-000000000002",'
              '"ts":"2026-05-01T00:00:00.000Z"}')
    sig = sodium.crypto_sign(record.encode(), sk_e)[:64]
    out["audit_sig"] = [{
        "id": "sig-001",
        "ed25519_priv_hex": hx(sk_e),
        "ed25519_pub_hex":  hx(pk_e),
        "record_canonical_json": record,
        "expected_sig_hex": hx(sig),
    }]

    json.dump(out, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
