-- Add `auto_generated` flag to vault_items so server-created rows (Stripe webhook
-- estate package entries, document processor PDF pointers) are excluded from the
-- E2EE backfill counter. These rows are intentionally plaintext: the platform
-- generated their content and they only point at a storage path. They would
-- otherwise wedge the "Securing your vault…" banner for every new user.

ALTER TABLE public.vault_items
  ADD COLUMN IF NOT EXISTS auto_generated boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS vault_items_auto_generated_idx
  ON public.vault_items (client_id, auto_generated);

-- Backfill existing rows: anything stamped with an order_id (auto-generated by
-- the Stripe webhook or doc processor) gets flagged so it stops counting toward
-- the backfill banner.
UPDATE public.vault_items
SET auto_generated = true
WHERE auto_generated = false
  AND (data ->> 'order_id') IS NOT NULL;
